typedef enum {
  ADC_CLK_BELOW_6MHZ = 0x0u,
  ADC_CLK_BELOW_12MHZ = 0x1u,
  ADC_CLK_BELOW_25MHZ = 0x2u,
  ADC_CLK_BELOW_50MHZ = 0x3u
} ___ADC_BOOST_Enum;

typedef enum {
  ADC_CAL_SINGLEENDED,
  ADC_CAL_DIFFERENTIAL
} ___ADC_CAL_DIF_Enum;

typedef enum {
  ADC_REGULAR,
  ADC_DMA_ONE_SHOT,
  ADC_DFSDM,
  ADC_DMA_CIRCULAR
} ___ADC_DMNGT_Enum;

typedef enum {
  ADC_RES_16BITS = 0x0u,
  ADC_RES_14BITS_LEGACY = 0x1u,
  ADC_RES_12BITS_LEGACY = 0x2u,
  ADC_RES_10BITS = 0x3u,
  ADC_RES_14BITS = 0x5u,
  ADC_RES_12BITS = 0x6u,
  ADC_RES_8BITS = 0x7u
} ___ADC_RES_Enum;

typedef enum {
  ADC_TRIG_DISABLED,
  ADC_TRIG_RISING,
  ADC_TRIG_FALLING,
  ADC_TRIG_RISING_FALLING
} ___ADC_TRIG_Enum;

typedef enum {
  ADC_DR_PRESERVE,
  ADC_DR_OVERWRITE
} ___ADC_OVRMOD_Enum;

typedef enum {
  ADC_CONT_SINGLECONV,
  ADC_CONT_CONTINUOUS
} ___ADC_CONT_Enum;

typedef enum {
  ADC_JSQR_QUEUE_NEVER_EMPTY,
  ADC_JSQR_QUEUE_ALLOW_EMPTY
} ___ADC_JSQRQM_Enum;

typedef enum {
  ADC_AWDG1_ALL_CHANNELS,
  ADC_AWDG1_SINGLE_CHANNEL
} ___ADC_AWDG1_SGL_Enum;

typedef enum {
  ADC_SMP_1P5_ADC_CLOCKCYCLES,
  ADC_SMP_2P5_ADC_CLOCKCYCLES,
  ADC_SMP_8P5_ADC_CLOCKCYCLES,
  ADC_SMP_16P5_ADC_CLOCKCYCLES,
  ADC_SMP_32P5_ADC_CLOCKCYCLES,
  ADC_SMP_64P5_ADC_CLOCKCYCLES,
  ADC_SMP_387P5_ADC_CLOCKCYCLES,
  ADC_SMP_810P5_ADC_CLOCKCYCLES
} ___ADC_SMP_Enum;

typedef enum {
  ADC_DUAL_INDEPENDENT,
  ADC_DUAL_COMBINED_REG_SIMULTANEOUS_INJ_SIMULTANEOUS = 0x0,
  ADC_DUAL_COMBINED_REG_SIMULTANEOUS_ALT_TRIGGER = 0x1,
  ADC_DUAL_COMBINED_INTERLEAVED_INJ_SIMULTANEOUS = 0x2,
  ADC_DUAL_INJ_ONLY = 0x5,
  ADC_DUAL_REG_ONLY = 0x6,
  ADC_DUAL_INTERLEAVED_ONLY = 0x7,
  ADC_DUAL_ALT_TRIGGER_ONLY = 0x9
} ___ADC_DUAL_Enum;

typedef enum {
  ADC_DATA_NOPACK = 0x0,
  ADC_DATA_32DOWNTO10 = 0x2,
  ADC_DATA_8BIT = 0x3
} ___ADC_DAMDF_Enum;

typedef enum {
  ADC_CLOCK_ASYNC,
  ADC_CLOCK_DIV1,
  ADC_CLOCK_DIV2,
  ADC_CLOCK_DIV4
} ___ADC_CKMODE_Enum;

typedef enum {
  ADC_PRESC_DIV1,
  ADC_PRESC_DIV2,
  ADC_PRESC_DIV4,
  ADC_PRESC_DIV6,
  ADC_PRESC_DIV8,
  ADC_PRESC_DIV10,
  ADC_PRESC_DIV12,
  ADC_PRESC_DIV16,
  ADC_PRESC_DIV32,
  ADC_PRESC_DIV64,
  ADC_PRESC_DIV128,
  ADC_PRESC_DIV256
} ___ADC_PRESC_Enum;