#ifdef _MSC_VER
#include "..\Temp_Defines\Temp_Defines.h"
#endif
#ifdef ARMCM7
#include "..\Include\core_cm7.h"
#endif
#ifdef ARMCM4
#include "..\Include\core_cm4.h"
#endif

typedef struct {
    uint32_t VHBPCR;
    uint32_t VLCR;
    uint32_t VVSACR;
    uint32_t VVBPCR;
    uint32_t VVFPCR;
    uint32_t VVACR;
    uint32_t LCCR;
    uint32_t CMCR;
    uint32_t GHCR;
    uint32_t GPDR;
    uint32_t GPSR;
    uint32_t TCCR[6];
    uint32_t CLCR;
    uint32_t CLTCR;
    uint32_t DLTCR;
    uint32_t PCTLR;
    uint32_t PCCONFR;
    uint32_t PUCR;
    uint32_t PTTCR;
    uint32_t PSR;
    uint32_t RESERVED0[2];
    uint32_t ISR[2];
    uint32_t IER[2];
    uint32_t RESERVED1[7];
    uint32_t FIR[2];
    uint32_t RESERVED2[8];
    uint32_t VSCR;
    uint32_t RESERVED3[2];
    uint32_t LCVCIDR;
    uint32_t LCCCR;
    uint32_t RESERVED4;
    uint32_t LPCMMR;
    uint32_t RESERVED5[7];
    uint32_t VMCCR;
    uint32_t VPCCR;
    uint32_t VCCCR;
    uint32_t VNPCCR;
    uint32_t VHSACCR;
    uint32_t VHBPCCR;
    uint32_t VLCCR;
    uint32_t VVSACCR;
    uint32_t VVBPCCR;
    uint32_t VVFPCCR;
    uint32_t VVACCR;
    uint32_t RESERVED6[167];
    uint32_t WCFGR;
    uint32_t WCR;
    uint32_t WIER;
    uint32_t WISR;
    uint32_t WIFCR;
    uint32_t RESERVED7;
    uint32_t WPCR[5];
    uint32_t RESERVED8;
    uint32_t WRPCR;
} DSIHOST_TypeDef;