#include "MemDefines.h"
#include "Periph_Regs\Regs_Top.h"

#define pADC1 (ADC_TypeDef *)ADC1_ADC2_BASE
#define pADC2 (ADC_TypeDef *)(ADC1_ADC2_BASE+0x100)
#define pADC3 (ADC_TypeDef *)ADC3_BASE
#define pADC12_COMMON (ADC_CommonTypeDef *)(ADC1_ADC2_BASE+0x300)
#define pADC3_COMMON (ADC_CommonTypeDef *)(ADC3_BASE+0x300)
#define pART (ART_TypeDef *)ART_CTRL_BASE
#define pBDMA (BDMA_TypeDef *)BDMA_BASE
#define pCOMP (COMP_TypeDef *)COMP_BASE
#define pCRC (CRC_TypeDef *)CRC_BASE
#define pCRYPTO (CRYPTO_TypeDef *)CRYPTO_BASE
#define pDAC (DAC_TypeDef *)DAC1_BASE
#define pDCMI (DCMI_TypeDef *)DCMI_BASE
#define pDFSDM (DFSDM_TypeDef *)DFSDM1_BASE
#define pDMA1 (DMA_TypeDef *)DMA1_BASE
#define pDMA2 (DMA_TypeDef *)DMA2_BASE
#define pDMA2D (DMA2D_TypeDef *)DMA2D_BASE
#define pDMAMUX1 (DMAMUX_TypeDef *)DMAMUX1_BASE
#define pDMAMUX2 (DMAMUX_TypeDef *)DMAMUX2_BASE
#define pDSIHOST (DSIHOST_TypeDef *)DSIHOST_BASE
#define pEXTI (EXTI_TypeDef *)EXTI_BASE
#define pFDCAN1 (FDCAN_TypeDef *)FDCAN1_BASE
#define pFDCAN2 (FDCAN_TypeDef *)FDCAN2_BASE
#define pFLASH (FLASH_TypeDef *)FLASH_INTERFACE_BASE
#define pFMC (FMC_TypeDef *)FMC_CTRL_BASE
#define pGPIOA (GPIO_TypeDef *)GPIOA_BASE
#define pGPIOB (GPIO_TypeDef *)GPIOB_BASE
#define pGPIOC (GPIO_TypeDef *)GPIOC_BASE
#define pGPIOD (GPIO_TypeDef *)GPIOD_BASE
#define pGPIOE (GPIO_TypeDef *)GPIOE_BASE
#define pGPIOF (GPIO_TypeDef *)GPIOF_BASE
#define pGPIOG (GPIO_TypeDef *)GPIOG_BASE
#define pGPIOH (GPIO_TypeDef *)GPIOH_BASE
#define pGPIOI (GPIO_TypeDef *)GPIOI_BASE
#define pGPIOJ (GPIO_TypeDef *)GPIOJ_BASE
#define pGPIOK (GPIO_TypeDef *)GPIOK_BASE
#define pHASH (HASH_TypeDef *)HASH_BASE
#define pHRTIM (HRTIM_TypeDef *)HRTIM_BASE
#define pHSEM (HSEM_TypeDef *)HSEM_BASE
#define pI2C1 (I2C_TypeDef *)I2C1_BASE
#define pI2C2 (I2C_TypeDef *)I2C2_BASE
#define pI2C3 (I2C_TypeDef *)I2C3_BASE
#define pI2C4 (I2C_TypeDef *)I2C4_BASE
#define pI2S1 (I2S_TypeDef *)SPI1_I2S1_BASE
#define pI2S2 (I2S_TypeDef *)SPI2_I2S2_BASE
#define pI2S3 (I2S_TypeDef *)SPI3_I2S3_BASE
#define pIWDG1 (IWDG_TypeDef *)IWDG1_BASE
#define pIWDG2 (IWDG_TypeDef *)IWDG2_BASE
#define pJPEG (JPEG_TypeDef *)JPEG_BASE
#define pLPTIM1 (LPTIM_TypeDef *)LPTIM1_BASE
#define pLPTIM2 (LPTIM_TypeDef *)LPTIM2_BASE
#define pLPTIM3 (LPTIM_TypeDef *)LPTIM3_BASE
#define pLPTIM4 (LPTIM_TypeDef *)LPTIM4_BASE
#define pLPTIM5 (LPTIM_TypeDef *)LPTIM5_BASE
#define pLPUART (LPUART_TypeDef *)LPUART1_BASE
#define pLTDC (LTDC_TypeDef *)LTDC_BASE
#define pMDIOS (MDIOS_TypeDef *)MDIOS_BASE
#define pMDMA (MDMA_TypeDef *)MDMA_BASE
#define pOPAMP (OPAMP_TypeDef *)OPAMP_BASE
#define pOTG_HS (OTG_HS_TypeDef *)USB1_OTG_HS_BASE
#define pOTG_FS (OTG_HS_TypeDef *)USB2_OTG_FS_BASE
#define pPWR (PWR_TypeDef *)PWR_BASE
#define pQSPI (QSPI_TypeDef *)QSPI_CTRL_BASE
#define pRAMECC1 (RAMECC_TypeDef *)RAMECC1_BASE
#define pRAMECC2 (RAMECC_TypeDef *)RAMECC2_BASE
#define pRAMECC3 (RAMECC_TypeDef *)RAMECC3_BASE
#define pRCC (RCC_TypeDef *)RCC_BASE
#define pSAI1 (SAI_TypeDef *)SAI1_BASE
#define pSAI2 (SAI_TypeDef *)SAI2_BASE
#define pSAI3 (SAI_TypeDef *)SAI3_BASE
#define pSAI4 (SAI_TypeDef *)SAI4_BASE
#define pSDMMC1 (SDMMC_TypeDef *)SDMMC1_BASE
#define pSDMMC2 (SDMMC_TypeDef *)SDMMC2_BASE
#define pSPDIFRX (SPDIFRX_TypeDef *)SPDIFRX_BASE
#define pSPI1 (SPI_TypeDef *)SPI1_I2S1_BASE
#define pSPI2 (SPI_TypeDef *)SPI2_I2S2_BASE
#define pSPI3 (SPI_TypeDef *)SPI3_I2S3_BASE
#define pSPI4 (SPI_TypeDef *)SPI4_BASE
#define pSPI5 (SPI_TypeDef *)SPI5_BASE
#define pSPI6 (SPI_TypeDef *)SPI6_BASE
#define pSWPMI (SWPMI_TypeDef *)SWPMI_BASE
#define pSYSCFG (SYSCFG_TypeDef *)SYSCFG_BASE
#define pTIM1 (Timer_TypeDef *)TIM1_BASE
#define pTIM2 (Timer_TypeDef *)TIM2_BASE
#define pTIM3 (Timer_TypeDef *)TIM3_BASE
#define pTIM4 (Timer_TypeDef *)TIM4_BASE
#define pTIM5 (Timer_TypeDef *)TIM5_BASE
#define pTIM6 (Timer_TypeDef *)TIM6_BASE
#define pTIM7 (Timer_TypeDef *)TIM7_BASE
#define pTIM8 (Timer_TypeDef *)TIM8_BASE
#define pTIM9 (Timer_TypeDef *)TIM9_BASE
#define pTIM10 (Timer_TypeDef *)TIM10_BASE
#define pTIM11 (Timer_TypeDef *)TIM11_BASE
#define pTIM12 (Timer_TypeDef *)TIM12_BASE
#define pTIM13 (Timer_TypeDef *)TIM13_BASE
#define pTIM14 (Timer_TypeDef *)TIM14_BASE
#define pTIM15 (Timer_TypeDef *)TIM15_BASE
#define pTIM16 (Timer_TypeDef *)TIM16_BASE
#define pTIM17 (Timer_TypeDef *)TIM17_BASE
#define pUSART1 (USART_TypeDef *)USART1_BASE
#define pUSART2 (USART_TypeDef *)USART2_BASE
#define pUSART3 (USART_TypeDef *)USART3_BASE
#define pUART4 (USART_TypeDef *)UART4_BASE
#define pUART5 (USART_TypeDef *)UART5_BASE
#define pUSART6 (USART_TypeDef *)USART6_BASE
#define pVREFBUF (VREF_TypeDef *)VREF_BASE
#define pWWDG1 (WWDG_TypeDef *)WWDG1_BASE
#define pWWDG2 (WWDG_TypeDef *)WWDG2_BASE